In [603]:
import numpy as np

# Defining both the matrices
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

# Performing division using arithmetic operators
div_ans = a/b
print(div_ans)

# Performing division using numpy functions
div_ans = np.divide(a, b)
print(div_ans)


[ 2.5        14.4         1.3         3.33333333]
[ 2.5        14.4         1.3         3.33333333]


In [604]:
# Performing mod on two matrices
mod_ans = np.mod(a, b)
print(mod_ans)

#Performing remainder on two matrices
rem_ans=np.remainder(a,b)
print(rem_ans)

# Performing power of two matrices
pow_ans = np.power(a, b)
print(pow_ans)

[ 1  2  3 10]
[ 1  2  3 10]
[                 25          1934917632        137858491849
 1152921504606846976]


8.7_numpy_arithmetic_operations.ipynb

In [605]:
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

# Performing multiplication using arithmetic operator
mul_ans = a*b
print(mul_ans)

# Performing multiplication using numpy function
mul_ans = np.multiply(a, b)
print(mul_ans)

[  10  360  130 3000]
[  10  360  130 3000]


numpy_arithmetic_operations

In [606]:
import numpy as np

# Defining both the matrices
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

# Performing addition using arithmetic operator
add_ans = a+b
print(add_ans)

# Performing addition using numpy function
add_ans = np.add(a, b)
print(add_ans)

# this would work
c = np.array([1, 2, 3, 4])
add_ans = a+b+c
print(add_ans)

# but here NumPy only considers the first two arrays (a and b) and ignores the third one (c).
add_ans = np.add(a, b, c)
print(add_ans)
     

[  7  77  23 130]
[  7  77  23 130]
[  8  79  26 134]
[  7  77  23 130]


In [607]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)

print(newarr)

[-10  -1   8  17  26  35]


In [608]:
# Defining both the matrices
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

# Performing subtraction using arithmetic operator
sub_ans = a-b
print(sub_ans)

# Performing subtraction using numpy function
sub_ans = np.subtract(a, b)
print(sub_ans)
     

[ 3 67  3 70]
[ 3 67  3 70]


In [609]:
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

# Performing multiplication using arithmetic operator
mul_ans = a*b
print(mul_ans)

# Performing multiplication using numpy function
mul_ans = np.multiply(a, b)
print(mul_ans)

[  10  360  130 3000]
[  10  360  130 3000]


MODULE_8.5_NUMPY

In [610]:
import numpy as np
a = np.arange(12).reshape(3, 4)
print(a)
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]

print(np.ravel(a))
# [ 0  1  2  3  4  5  6  7  8  9 10 11]

print(type(np.ravel(a)))
# 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
<class 'numpy.ndarray'>


In [611]:

print(np.ravel([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]))


print(type(np.ravel([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])))
     

[ 0  1  2  3  4  5  6  7  8  9 10 11]
<class 'numpy.ndarray'>


Module_8.10_Numpy_slicing_indexing

In [612]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])  # Output: 1
print(arr[2])  # Output: 3


1
3


In [613]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[1:4])  # Output: [2 3 4]
print(arr[:3])   # Output: [1 2 3]
print(arr[::2])  # Output: [1 3 5]

[2 3 4]
[1 2 3]
[1 3 5]


Module_8.8.1_Numpy_upcasting.

In [614]:
arr = np.array([1, 2, 3])
scalar = 2
result = arr + scalar
print(result)

[3 4 5]


In [615]:

arr_int = np.array([1, 2, 3])
arr_float = np.array([1.5, 2.5, 3.5])
result = arr_int + arr_float
print(result)  # Output: [2.5 4.5 6.5]


[2.5 4.5 6.5]


In [616]:
a = 5
b = 3

result = np.add(a, b)
print(result)

8


8.9_Conditional_Operators.ipynb

In [617]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])
x
     

array([1, 2, 3, 4, 5])

In [618]:
x < 3  # less than

array([ True,  True, False, False, False])

In [619]:
x > 3  # greater than

array([False, False, False,  True,  True])

In [620]:
x <= 3  # less than or equal
     

array([ True,  True,  True, False, False])

In [621]:
x >= 3  # greater than or equal

array([False, False,  True,  True,  True])

In [622]:

x != 3  # not equal
     

array([ True,  True, False,  True,  True])

In [623]:
x == 3  # equal

array([False, False,  True, False, False])

In [624]:

(2 * x) == (x ** 2)

array([False,  True, False, False, False])

In [625]:

rng = np.random.default_rng(seed=1701)
x = rng.integers(10, size=(3, 4))
x

array([[9, 4, 0, 3],
       [8, 6, 3, 1],
       [3, 7, 4, 0]])

In [626]:
x < 6

array([[False,  True,  True,  True],
       [False, False,  True,  True],
       [ True, False,  True,  True]])

In [627]:
print(x)

[[9 4 0 3]
 [8 6 3 1]
 [3 7 4 0]]


In [628]:
# how many values less than 6?
np.count_nonzero(x < 6)

np.int64(8)

In [629]:
np.sum(x < 6)

np.int64(8)

In [630]:
# how many values less than 6 in each row?
np.sum(x < 6, axis=1)

array([3, 2, 3])

In [631]:
# are there any values greater than 8?
np.any(x > 8)

np.True_

In [632]:
# are there any values less than zero?
np.any(x < 0)
     

np.False_

In [633]:
# are all values less than 10?
np.all(x < 10)

np.True_

In [634]:
# are all values equal to 6?
np.all(x == 6)

np.False_

In [635]:
# are all values in each row less than 8?
np.all(x < 8, axis=1)
     

array([False, False,  True])

In [636]:
x

array([[9, 4, 0, 3],
       [8, 6, 3, 1],
       [3, 7, 4, 0]])

In [637]:

x < 5

array([[False,  True,  True,  True],
       [False, False,  True,  True],
       [ True, False,  True,  True]])

In [638]:
x[x < 5]

array([4, 0, 3, 3, 1, 3, 4, 0])

In [639]:
bool(42), bool(0)

(True, False)

In [640]:
bool(42 and 0)

False

In [641]:
bool(42 or 0)

True

In [642]:
bin(42)

'0b101010'

In [643]:
bin(59)

'0b111011'

In [644]:
bin(42 & 59)
     

'0b101010'

In [645]:
bin(42 | 59)
     

'0b111011'

In [646]:
A = np.array([1, 0, 1, 0, 1, 0], dtype=bool)
B = np.array([1, 1, 1, 0, 1, 1], dtype=bool)
A | B

array([ True,  True,  True, False,  True,  True])

In [647]:
x = np.arange(10)
(x > 4) & (x < 8)

array([False, False, False, False, False,  True,  True,  True, False,
       False])

                                       Numpy_8.3Numpy_creation.ipynb


In [648]:
import numpy as np
x = np.array([1, 2, 3])
print(type(x))
print(x)
print(x.dtype)

<class 'numpy.ndarray'>
[1 2 3]
int64


In [649]:
x = np.array([1.0, 2, 3])
print(x.dtype)

float64


In [650]:
import numpy as np
x = np.array([1, 2, 3])
print(x.shape)
print(f"Number of dimensions: {len(x.shape)}")
print(f"Length of array: {x.shape[0]}")

(3,)
Number of dimensions: 1
Length of array: 3


In [651]:
print(x[0])  # first value in the array
1
print(x[1])  # second value in the array
2

1
2


2

In [652]:
x[2] = 100
print(x)

[  1   2 100]


In [653]:
x = np.array([0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(x[2:4])  # get values from indexes 2 and 3
print()
print(x[4::2])
print()  # get values from index 4 to the end in steps of 2
x[0:3] = [20, 19, 18]  # re-assign the first three values
print(x)

[20 30]

[ 40  60  80 100]

[ 20  19  18  30  40  50  60  70  80  90 100]


In [654]:
# Creating a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:")
print(arr_2d)

# Creating a 3D array
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Array:")
print(arr_3d)

2D Array:
[[1 2 3]
 [4 5 6]]
3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [655]:
x = np.zeros(10)  # an array of 10 zeros
print(x)

# Or, containing all ones (using the ones function):
x = np.ones(10)  # an array of 10 ones
print(x)


x = 2.3964 * np.ones(3)  # an array of 3 values of 2.3964
print(x)

# or equivalently
x = np.full(3, 2.3964)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[2.3964 2.3964 2.3964]
[2.3964 2.3964 2.3964]


In [656]:
# Create a 1D array filled with ones
ones_arr = np.ones(5)
print("1D Array filled with ones:")
print(ones_arr)

# Create a 2D array (2x3) filled with ones
ones_arr_2d = np.ones((2, 3))
print("2D Array (2x3) filled with ones:")
print(ones_arr_2d)

1D Array filled with ones:
[1. 1. 1. 1. 1.]
2D Array (2x3) filled with ones:
[[1. 1. 1.]
 [1. 1. 1.]]


numpy_8.2._Math_Refresher_.ipynb

In [657]:
import numpy as np

Data Dimensions
Scalars

In [658]:
s = np.array(5)

In [659]:
s.shape

()

In [660]:
x = s + 3

In [661]:
x.shape 

()

Vectors

In [662]:
v = np.array([1,2,3])
     

In [663]:
v.shape

(3,)

In [664]:
x = v[1]
     

In [665]:

v[1:]

array([2, 3])

Matrices

In [666]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
m.shape

(3, 3)

In [667]:
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],[[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])


In [668]:
t.shape

(3, 3, 2, 1)

In [669]:
t[2][1][1][0]
     

np.int64(16)

In [670]:
t[2,1,1,0]
     

np.int64(16)

Changing Shapes

In [671]:
v = np.array([1,2,3,4])

In [672]:

x = v.reshape(1,4)
x

array([[1, 2, 3, 4]])

In [673]:
x = v[None,:]

In [674]:
x

array([[1, 2, 3, 4]])

In [675]:
x = v[:,None]   

In [676]:
x

array([[1],
       [2],
       [3],
       [4]])

Matrix Multiplication
Element-wise

In [677]:
m = np.array([[1,2,3],[4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [678]:
n = m * 0.25
n

array([[0.25, 0.5 , 0.75],
       [1.  , 1.25, 1.5 ]])

In [679]:
m * n

array([[0.25, 1.  , 2.25],
       [4.  , 6.25, 9.  ]])

In [680]:
np.multiply(m,n)

array([[0.25, 1.  , 2.25],
       [4.  , 6.25, 9.  ]])

Product

In [681]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [682]:
a.shape

(2, 4)

In [683]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [684]:
b.shape

(4, 3)

In [685]:
c = np.matmul(a,b)
c

array([[ 70,  80,  90],
       [158, 184, 210]])

In [686]:
c.shape
     

(2, 3)

dot function

In [687]:
a = np.array([[1,2],[3,4]])
a
     

array([[1, 2],
       [3, 4]])

In [688]:
np.dot(a,a)
     

array([[ 7, 10],
       [15, 22]])

In [689]:
a.dot(a)

array([[ 7, 10],
       [15, 22]])

In [690]:
np.matmul(a,a)

array([[ 7, 10],
       [15, 22]])

Transpose

In [691]:
m = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [692]:
m.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [693]:
m_t = m.T

In [694]:
m_t[3][1] = 200

In [695]:
m_t

array([[  1,   5,   9],
       [  2,   6,  10],
       [  3,   7,  11],
       [  4, 200,  12]])

In [696]:
m

array([[  1,   2,   3,   4],
       [  5,   6,   7, 200],
       [  9,  10,  11,  12]])

real use case

In [697]:
inputs = np.array([[-0.27,0.45,0.64,0.31]])
inputs

array([[-0.27,  0.45,  0.64,  0.31]])

In [698]:
inputs.shape

(1, 4)

In [699]:
weights = np.array([[0.02,0.001,-0.03,0.036],[0.04, -0.003, 0.025, 0.009], [0.012, -0.045, 0.28, -0.067]])
weights

array([[ 0.02 ,  0.001, -0.03 ,  0.036],
       [ 0.04 , -0.003,  0.025,  0.009],
       [ 0.012, -0.045,  0.28 , -0.067]])

In [700]:
weights.shape

(3, 4)

In [701]:
np.matmul(inputs,weights.T)

array([[-0.01299,  0.00664,  0.13494]])